### ISSUE TITLE
open chrome apps 

### ISSUE THREAD

**Issue by TWART016** [fdarveau/flame#13]
**Deployment details:**
- App version: 2.2.0
- Docker image tag: latest

---

**Bug description:**
I want to open the chrome apps as a bookmark
`chrome://apps
`

The website does not open. I can't see an error.

**Comment by fdarveau** [comment]
Unfortunately, it seems to be a browser limitation, as mentioned here : https://stackoverflow.com/a/40364397

I tested it by adding 2 bookmarks with "special" protocols in the URL :
![image](https://user-images.githubusercontent.com/6851146/148716833-e60f6727-5369-4424-94fe-b2503e6df321.png)

On the first one (`chrome://test`) no tooltip shows up at the bottom of the page like a normal link, even if the `href` is set (see screenshot above) : 
![image](https://user-images.githubusercontent.com/6851146/148716882-9019156e-61dc-4e23-85fb-391ae11fcc14.png)

On the second one (`vscode://test`), the tooltip showing the URL appears, as expected : 
![image](https://user-images.githubusercontent.com/6851146/148716943-87422b8a-2209-4588-8373-8d91fa0aa7f2.png)



I also looked in the main repository, and it seems to have been discussed when working on supporting more than just `http` and `https`, with the same conclusion : 
- https://github.com/pawelmalak/flame/issues/62
- https://github.com/pawelmalak/flame/issues/74
- https://github.com/pawelmalak/flame/pull/81
