### ISSUE TITLE
Ability to reorder Bookmarks 

### ISSUE THREAD

**Issue by adrianmihalko** [fdarveau/flame#17]
Hi,

I am using yourt fork, because I like to use categories in Applications. I would like to ask if it is possible to reorder bookmarks, applications?

Regards,
Adrian

**Comment by fdarveau** [comment]
Yes, it is possible to reorder bookmarks, applications and categories.

Make sure the sort order is set to "Custom order" in the General settings :
![image](https://user-images.githubusercontent.com/6851146/218795498-2895e19a-98fd-47c7-a383-7c23e5fee7dc.png)

Once that is set, you should be able to drag and drop items in the Applications, Bookmarks and Categories edition pages.

**Comment by adrianmihalko** [comment]
Thanks, I enabled.

The only place I got it working is in the edit categories page:

https://user-images.githubusercontent.com/733361/218801356-1075aa93-e082-4a23-8ce9-b79aee466ad4.mov

For some reason I can't reorder apps.

**Comment by fdarveau** [comment]
Sorry, I should have been a little more clear.

The "Edit applications" and "Edit bookmarks" pages are accessed by clicking the category header.
![Screenshots_2023-02-14-11-45-53](https://user-images.githubusercontent.com/6851146/218802222-bcb82d4b-bdef-464a-9fa6-a3928748c4a2.png)

Once in that page, you get a table like the one in the Edit Categories page.

**Comment by adrianmihalko** [comment]
Ahh, got it. It's working flawlessly. Thank you.
