### ISSUE TITLE
Multiarch Image Pull

### ISSUE THREAD

**Issue by bsmithuk** [fdarveau/flame#18]
**Deployment details:**
- App version: latest
- Platform: arm 
- Docker image tag [e.g. latest, multiarch]: 

---

**Bug description:**

No image exists when pulling from ghcr.io/fdarveau/flame:latest:multiarch 
---

**Steps to reproduce:**
Assume fork no longer being maintained? Gutted as App categories is the only bit missing from Flame! Works on intel cpu though. Docker-compose.yml listed below:
version: '3.6'

services:
  flame:
    image: ghcr.io/fdarveau/flame:latest:multiarch
    container_name: flame
    volumes:
      - /fileLocationOnServer:/app/data:z
    ports:
      - 5005:5005
    environment:
      - PASSWORD=<Redacted>
    restart: unless-stopped

**Comment by fdarveau** [comment]
Sorry, there was an error in the README that I didn't notice and was not reported yet.

You should replace the line `image: ghcr.io/fdarveau/flame:latest:multiarch` with either `image: ghcr.io/fdarveau/flame:latest` or `image: ghcr.io/fdarveau/flame:latest-multiarch`, depending on what platform you run Docker.

I did not have a multiarch image implemented, but it is now available :)
