### ISSUE TITLE
Allow container to run rootless

### ISSUE THREAD

**Issue by codersaur** [fdarveau/flame#28]
I'd like to run flame rootless. I tried adding `user: 1000:1000` to the docker compose definition...

    flame:
      container_name: flame
      image: ghcr.io/fdarveau/flame:latest 
      user: 1000:1000
      ...

But this results in permission errors for resources inside the container and flame won't start:

`Error: EACCES: permission denied, open '/app/public/flame.css`

If you can make the image compatible with running rootless that'd be great. (It does seem that user 1000 and group 1000 are already created in image...)

**Comment by fdarveau** [comment]
Hello, sorry for the delay.

Can you try the `ghcr.io/fdarveau/flame:rootless-support` image and confirm everything is working as you expect?

On my end, it does not seem to cause breaking changes with an existing container and going into the container's terminal shows it running as the "node" user (created as UID/GID 1000 by the base node images) :
![image](https://github.com/user-attachments/assets/34cf71fe-b766-4b4c-b822-aafbeebec76b)


I will merge this PR once you can confirm everything works.

**Comment by codersaur** [comment]
> I will merge this PR once you can confirm everything works.

Looks good to me. Have tested creating and editing apps/links and ps shows it's running as node. Thanks.

**Comment by fdarveau** [comment]
Great!

The PR is merged and the `latest` tag should be updated in a few minutes.
